ALTER TABLE "communities" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
ALTER TABLE "faculties" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
ALTER TABLE "courses" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
ALTER TABLE "scholarships" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
ALTER TABLE "subjects" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
ALTER TABLE "universities" ADD COLUMN IF NOT EXISTS "gradient" VARCHAR(255) DEFAULT '';
